### ISSUE TITLE
r2d2-arangors crashes alpine docker container

### ISSUE THREAD

**Issue by Weasy666** [inzanez/r2d2-arangors#2]
I am building an application with my [Rocket fork](https://github.com/Weasy666/Rocket), because of the there added `arango_pool` feature. When i run the application locally, then everything is working fine, it opens a connection to a ArangoDB docker container and works flawlessly with it.
I then went on to also build a docker image for my application, an `alpine-3.12` image. And here starts my problem.
Building the application with `musl` as target was no problem, but as soon as the container starts and a `r2d2` pool is build and connect to the `ArangoDB` container, then my app container crashs with the following failure.

```bash
test_1  | pool(db_name: catalog, rocket: _): Building r2d2::Pool
test_1  | Establish with jwt
test_1  | Establish with jwt
test_1  | Establish with jwt
test_1  | registering with poller
test_1  | (ThreadId(13)) park without timeout
test_1  | (ThreadId(11)) park without timeout
test_1  | registering with poller
test_1  | (ThreadId(12)) park without timeout
test_1  | (ThreadId(16)) start runtime::block_on
test_1  | (ThreadId(14)) start runtime::block_on
test_test_1 exited with code 139
```

I have narrowed it down to `r2d2-arangors`, or it does at least look like that, because when i do the same with Rocket's `postgres_pool` and a `postgresql` container everything just works. And the `pool(db_name: catalog, rocket: _): Building r2d2::Pool` line is a `println` i added above this line https://github.com/Weasy666/Rocket/blob/2763ad3a10d11d5517ea2eef96598be54f73ab36/contrib/lib/src/databases.rs#L748.

**Comment by inzanez** [comment]
Hi

I have many apps running in Docker and Kubernetes based on alpine images, using r2d2 arangors. So I think its highly unlikely that it is the lib.

But somehow that 139 looks familiar. Could you send me details to your docker container? Dockerfile maybe? And maybe the lines of code where you spawn and use the pool.

Ok. So what I'd need is a minimal running example (including Dockerfile) that I can use with your forked repo. That way, I can try finding out what might be missing. In addition, it would be nice getting the exact build parameters (how you build your rust application code; static OpenSSL?, Dynamic?).

**Comment by Weasy666** [comment]
Ok, i will create a MRE tomorrow, with `Dockerfile` and `docker-compose.yml` and link it here.

**Comment by Weasy666** [comment]
Had the time to do it today, see https://github.com/Weasy666/arangors-mre

**Comment by inzanez** [comment]
@Weasy666 Well, funny part is: I cannot tell you right now what's happening inside your image. I suppose that something with OpenSSL or another LD is not right somehow. I adapted your build script a bit to build against statically compiled LibreSSL inside docker instead:
https://github.com/inzanez/arangors-mre

I can confirm that this works without any issues. Please let me know if that helps.

**Comment by Weasy666** [comment]
Heh...the pitfalls of building something 😅
Thanks for the help!
Nevertheless, i think i will open a PR at `arangors` to switch `reqwest` to `rustls`, or at least add a feature flag to be able to switch between `OpenSSL` and `rustls`, so that other won't have the same problem.

**Comment by Weasy666** [comment]
Oh man...i had another idea and replaced `openssl-dev` with `libressl-dev` and...you see...it just works 😐
Sorry for stealing your time and again thanks for the help.

**Comment by inzanez** [comment]
@Weasy666 Ok, so you tracked it down to `OpenSSL` vs `rustls` then? That's good to know!

**Comment by Weasy666** [comment]
Yes, it is working with an `arangors` that uses `reqwest` with the `rustls-tls` feature. So i think we can close this issue, as it is an upstream problem.
